add_test([=[Account.Mock]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.Mock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.Mock]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Account.Init]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.Init]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.Init]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Account.GetBalance]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.GetBalance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.GetBalance]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Account.ChangeBalance]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.ChangeBalance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.ChangeBalance]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Account.Lock]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.Lock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.Lock]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Account.Unlock]=]  /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build/banking_lib_test [==[--gtest_filter=Account.Unlock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Account.Unlock]=]  PROPERTIES WORKING_DIRECTORY /Users/LiWinDom/Documents/Code/timp/lab05/banking/cmake-build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  banking_lib_test_TESTS Account.Mock Account.Init Account.GetBalance Account.ChangeBalance Account.Lock Account.Unlock)
