name: Banking library

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure and build banking
        working-directory: ./banking/
        run: |
          cmake -S ./ -B ./build
          cmake --build ./build

      - name: Testing banking
        working-directory: ./banking/build/
        run: ./banking_lib_test